language: node_js

node_js:
  - 12

services:
  - docker

before_install:
  - docker build -f DockerfileDev -t dawidde/react_redux_app_dev .
  - docker build -t dawidde/react_redux_app .
  - docker run -d -p 80:80 dawidde/react_redux_app
  - docker run -d -p  3000:3000 dawidde/react_redux_app_dev

